version: '3.3'

services:
  nginx:
    build: ./src/main/java/com/titan/thor/nginx
    ports:
      - "8080:80"
    depends_on:
      - loki1
      - loki3
      - loki4
      - thor7
      - thor8
      - thor9

  loki4:
    restart: always
    image: ivorytoast3853/loki:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/titan?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: gt
    ports:
      - "8084:8084"

  loki3:
    restart: always
    image: ivorytoast3853/loki:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/titan?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: gt
    ports:
      - "8083:8084"

  loki1:
    restart: always
    image: ivorytoast3853/loki:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/titan?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: gt
    ports:
      - "8081:8084"

  bifrost:
    restart: always
    image: ivorytoast3853/bifrost

  thor7:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/titan?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: gt
    ports:
      - "8087:8084"

  thor8:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/titan?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: gt
    ports:
      - "8088:8084"

  thor9:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/titan?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: gt
    ports:
      - "8089:8084"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  db:
    image: mysql:latest
    container_name: mysql-db2
    environment:
      - MYSQL_ROOT_PASSWORD=gt
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - thor_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - "8082:80"
    depends_on:
      - db
    restart: always
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: gt

volumes:
  thor_data: